# Generated by Django 4.2.7 on 2023-11-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='links_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=20)),
                ('date', models.CharField(blank=True, max_length=20)),
                ('information', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=20)),
                ('information', models.CharField(blank=True, max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
