# Generated by Django 4.2.7 on 2023-11-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(blank=True, max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('code', models.CharField(max_length=6)),
                ('gmail', models.CharField(max_length=15)),
                ('code_sended', models.BooleanField(null=True)),
                ('gmail_verified', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='gmail_tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('email', models.CharField(max_length=20)),
                ('token', models.CharField(blank=True, max_length=15)),
                ('link_sended', models.BooleanField(null=True)),
                ('gmail_verified', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='links_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=20)),
                ('date', models.CharField(blank=True, max_length=20)),
                ('information', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=20)),
                ('information', models.CharField(blank=True, max_length=20)),
                ('ip_1', models.GenericIPAddressField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
