# Generated by Django 4.2.5 on 2023-09-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links_db',
            name='link',
            field=models.URLField(max_length=20),
        ),
    ]
