# Generated by Django 4.2.5 on 2023-09-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_links_db_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links_db',
            name='date_add',
            field=models.DateTimeField(blank=True),
        ),
    ]
