# Generated by Django 4.2.7 on 2023-11-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_users_ip_users_ip_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(blank=True, max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('code', models.CharField(max_length=6)),
            ],
        ),
    ]
