# Generated by Django 4.2.5 on 2023-09-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_links_db_date_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='links_db',
            name='date_add',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
