# Generated by Django 4.2.5 on 2023-09-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_links_db_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links_db',
            old_name='device',
            new_name='user_information',
        ),
    ]
