# Generated by Django 4.2.5 on 2023-09-12 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_rename_device_links_db_user_information'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links_db',
            old_name='date_add',
            new_name='date',
        ),
    ]
