# Generated by Django 4.2.5 on 2023-09-12 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_rename_date_add_links_db_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links_db',
            old_name='user_information',
            new_name='information',
        ),
    ]
